/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';
import { ADRENA_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const GET_EXIT_PRICE_AND_FEE_DISCRIMINATOR = new Uint8Array([
  73, 77, 94, 31, 8, 9, 92, 32,
]);

export function getGetExitPriceAndFeeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    GET_EXIT_PRICE_AND_FEE_DISCRIMINATOR
  );
}

export type GetExitPriceAndFeeInstruction<
  TProgram extends string = typeof ADRENA_PROGRAM_ADDRESS,
  TAccountCortex extends string | IAccountMeta<string> = string,
  TAccountPool extends string | IAccountMeta<string> = string,
  TAccountPosition extends string | IAccountMeta<string> = string,
  TAccountCustody extends string | IAccountMeta<string> = string,
  TAccountCustodyTradeOracle extends string | IAccountMeta<string> = string,
  TAccountCollateralCustody extends string | IAccountMeta<string> = string,
  TAccountCollateralCustodyOracle extends
    | string
    | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountCortex extends string
        ? ReadonlyAccount<TAccountCortex>
        : TAccountCortex,
      TAccountPool extends string
        ? ReadonlyAccount<TAccountPool>
        : TAccountPool,
      TAccountPosition extends string
        ? ReadonlyAccount<TAccountPosition>
        : TAccountPosition,
      TAccountCustody extends string
        ? ReadonlyAccount<TAccountCustody>
        : TAccountCustody,
      TAccountCustodyTradeOracle extends string
        ? ReadonlyAccount<TAccountCustodyTradeOracle>
        : TAccountCustodyTradeOracle,
      TAccountCollateralCustody extends string
        ? ReadonlyAccount<TAccountCollateralCustody>
        : TAccountCollateralCustody,
      TAccountCollateralCustodyOracle extends string
        ? ReadonlyAccount<TAccountCollateralCustodyOracle>
        : TAccountCollateralCustodyOracle,
      ...TRemainingAccounts,
    ]
  >;

export type GetExitPriceAndFeeInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type GetExitPriceAndFeeInstructionDataArgs = {};

export function getGetExitPriceAndFeeInstructionDataEncoder(): Encoder<GetExitPriceAndFeeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: GET_EXIT_PRICE_AND_FEE_DISCRIMINATOR,
    })
  );
}

export function getGetExitPriceAndFeeInstructionDataDecoder(): Decoder<GetExitPriceAndFeeInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getGetExitPriceAndFeeInstructionDataCodec(): Codec<
  GetExitPriceAndFeeInstructionDataArgs,
  GetExitPriceAndFeeInstructionData
> {
  return combineCodec(
    getGetExitPriceAndFeeInstructionDataEncoder(),
    getGetExitPriceAndFeeInstructionDataDecoder()
  );
}

export type GetExitPriceAndFeeInput<
  TAccountCortex extends string = string,
  TAccountPool extends string = string,
  TAccountPosition extends string = string,
  TAccountCustody extends string = string,
  TAccountCustodyTradeOracle extends string = string,
  TAccountCollateralCustody extends string = string,
  TAccountCollateralCustodyOracle extends string = string,
> = {
  /** #1 */
  cortex: Address<TAccountCortex>;
  /** #2 */
  pool: Address<TAccountPool>;
  /** #3 */
  position: Address<TAccountPosition>;
  /** #4 */
  custody: Address<TAccountCustody>;
  /** #5 */
  custodyTradeOracle: Address<TAccountCustodyTradeOracle>;
  /** #6 */
  collateralCustody: Address<TAccountCollateralCustody>;
  /** #7 */
  collateralCustodyOracle: Address<TAccountCollateralCustodyOracle>;
};

export function getGetExitPriceAndFeeInstruction<
  TAccountCortex extends string,
  TAccountPool extends string,
  TAccountPosition extends string,
  TAccountCustody extends string,
  TAccountCustodyTradeOracle extends string,
  TAccountCollateralCustody extends string,
  TAccountCollateralCustodyOracle extends string,
  TProgramAddress extends Address = typeof ADRENA_PROGRAM_ADDRESS,
>(
  input: GetExitPriceAndFeeInput<
    TAccountCortex,
    TAccountPool,
    TAccountPosition,
    TAccountCustody,
    TAccountCustodyTradeOracle,
    TAccountCollateralCustody,
    TAccountCollateralCustodyOracle
  >,
  config?: { programAddress?: TProgramAddress }
): GetExitPriceAndFeeInstruction<
  TProgramAddress,
  TAccountCortex,
  TAccountPool,
  TAccountPosition,
  TAccountCustody,
  TAccountCustodyTradeOracle,
  TAccountCollateralCustody,
  TAccountCollateralCustodyOracle
> {
  // Program address.
  const programAddress = config?.programAddress ?? ADRENA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    cortex: { value: input.cortex ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: false },
    position: { value: input.position ?? null, isWritable: false },
    custody: { value: input.custody ?? null, isWritable: false },
    custodyTradeOracle: {
      value: input.custodyTradeOracle ?? null,
      isWritable: false,
    },
    collateralCustody: {
      value: input.collateralCustody ?? null,
      isWritable: false,
    },
    collateralCustodyOracle: {
      value: input.collateralCustodyOracle ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.cortex),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.custody),
      getAccountMeta(accounts.custodyTradeOracle),
      getAccountMeta(accounts.collateralCustody),
      getAccountMeta(accounts.collateralCustodyOracle),
    ],
    programAddress,
    data: getGetExitPriceAndFeeInstructionDataEncoder().encode({}),
  } as GetExitPriceAndFeeInstruction<
    TProgramAddress,
    TAccountCortex,
    TAccountPool,
    TAccountPosition,
    TAccountCustody,
    TAccountCustodyTradeOracle,
    TAccountCollateralCustody,
    TAccountCollateralCustodyOracle
  >;

  return instruction;
}

export type ParsedGetExitPriceAndFeeInstruction<
  TProgram extends string = typeof ADRENA_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** #1 */
    cortex: TAccountMetas[0];
    /** #2 */
    pool: TAccountMetas[1];
    /** #3 */
    position: TAccountMetas[2];
    /** #4 */
    custody: TAccountMetas[3];
    /** #5 */
    custodyTradeOracle: TAccountMetas[4];
    /** #6 */
    collateralCustody: TAccountMetas[5];
    /** #7 */
    collateralCustodyOracle: TAccountMetas[6];
  };
  data: GetExitPriceAndFeeInstructionData;
};

export function parseGetExitPriceAndFeeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedGetExitPriceAndFeeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      cortex: getNextAccount(),
      pool: getNextAccount(),
      position: getNextAccount(),
      custody: getNextAccount(),
      custodyTradeOracle: getNextAccount(),
      collateralCustody: getNextAccount(),
      collateralCustodyOracle: getNextAccount(),
    },
    data: getGetExitPriceAndFeeInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
