/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';
import { ADRENA_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const GET_ENTRY_PRICE_AND_FEE_DISCRIMINATOR = new Uint8Array([
  134, 30, 231, 199, 83, 72, 27, 99,
]);

export function getGetEntryPriceAndFeeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    GET_ENTRY_PRICE_AND_FEE_DISCRIMINATOR
  );
}

export type GetEntryPriceAndFeeInstruction<
  TProgram extends string = typeof ADRENA_PROGRAM_ADDRESS,
  TAccountCortex extends string | IAccountMeta<string> = string,
  TAccountPool extends string | IAccountMeta<string> = string,
  TAccountCustody extends string | IAccountMeta<string> = string,
  TAccountCustodyTradeOracle extends string | IAccountMeta<string> = string,
  TAccountCollateralCustody extends string | IAccountMeta<string> = string,
  TAccountCollateralCustodyOracle extends
    | string
    | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountCortex extends string
        ? ReadonlyAccount<TAccountCortex>
        : TAccountCortex,
      TAccountPool extends string
        ? ReadonlyAccount<TAccountPool>
        : TAccountPool,
      TAccountCustody extends string
        ? ReadonlyAccount<TAccountCustody>
        : TAccountCustody,
      TAccountCustodyTradeOracle extends string
        ? ReadonlyAccount<TAccountCustodyTradeOracle>
        : TAccountCustodyTradeOracle,
      TAccountCollateralCustody extends string
        ? ReadonlyAccount<TAccountCollateralCustody>
        : TAccountCollateralCustody,
      TAccountCollateralCustodyOracle extends string
        ? ReadonlyAccount<TAccountCollateralCustodyOracle>
        : TAccountCollateralCustodyOracle,
      ...TRemainingAccounts,
    ]
  >;

export type GetEntryPriceAndFeeInstructionData = {
  discriminator: ReadonlyUint8Array;
  collateral: bigint;
  leverage: number;
  side: number;
};

export type GetEntryPriceAndFeeInstructionDataArgs = {
  collateral: number | bigint;
  leverage: number;
  side: number;
};

export function getGetEntryPriceAndFeeInstructionDataEncoder(): Encoder<GetEntryPriceAndFeeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['collateral', getU64Encoder()],
      ['leverage', getU32Encoder()],
      ['side', getU8Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: GET_ENTRY_PRICE_AND_FEE_DISCRIMINATOR,
    })
  );
}

export function getGetEntryPriceAndFeeInstructionDataDecoder(): Decoder<GetEntryPriceAndFeeInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['collateral', getU64Decoder()],
    ['leverage', getU32Decoder()],
    ['side', getU8Decoder()],
  ]);
}

export function getGetEntryPriceAndFeeInstructionDataCodec(): Codec<
  GetEntryPriceAndFeeInstructionDataArgs,
  GetEntryPriceAndFeeInstructionData
> {
  return combineCodec(
    getGetEntryPriceAndFeeInstructionDataEncoder(),
    getGetEntryPriceAndFeeInstructionDataDecoder()
  );
}

export type GetEntryPriceAndFeeInput<
  TAccountCortex extends string = string,
  TAccountPool extends string = string,
  TAccountCustody extends string = string,
  TAccountCustodyTradeOracle extends string = string,
  TAccountCollateralCustody extends string = string,
  TAccountCollateralCustodyOracle extends string = string,
> = {
  /** #1 */
  cortex: Address<TAccountCortex>;
  /** #2 */
  pool: Address<TAccountPool>;
  /** #3 */
  custody: Address<TAccountCustody>;
  /** #4 */
  custodyTradeOracle: Address<TAccountCustodyTradeOracle>;
  /** #5 */
  collateralCustody: Address<TAccountCollateralCustody>;
  /** #6 */
  collateralCustodyOracle: Address<TAccountCollateralCustodyOracle>;
  collateral: GetEntryPriceAndFeeInstructionDataArgs['collateral'];
  leverage: GetEntryPriceAndFeeInstructionDataArgs['leverage'];
  side: GetEntryPriceAndFeeInstructionDataArgs['side'];
};

export function getGetEntryPriceAndFeeInstruction<
  TAccountCortex extends string,
  TAccountPool extends string,
  TAccountCustody extends string,
  TAccountCustodyTradeOracle extends string,
  TAccountCollateralCustody extends string,
  TAccountCollateralCustodyOracle extends string,
  TProgramAddress extends Address = typeof ADRENA_PROGRAM_ADDRESS,
>(
  input: GetEntryPriceAndFeeInput<
    TAccountCortex,
    TAccountPool,
    TAccountCustody,
    TAccountCustodyTradeOracle,
    TAccountCollateralCustody,
    TAccountCollateralCustodyOracle
  >,
  config?: { programAddress?: TProgramAddress }
): GetEntryPriceAndFeeInstruction<
  TProgramAddress,
  TAccountCortex,
  TAccountPool,
  TAccountCustody,
  TAccountCustodyTradeOracle,
  TAccountCollateralCustody,
  TAccountCollateralCustodyOracle
> {
  // Program address.
  const programAddress = config?.programAddress ?? ADRENA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    cortex: { value: input.cortex ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: false },
    custody: { value: input.custody ?? null, isWritable: false },
    custodyTradeOracle: {
      value: input.custodyTradeOracle ?? null,
      isWritable: false,
    },
    collateralCustody: {
      value: input.collateralCustody ?? null,
      isWritable: false,
    },
    collateralCustodyOracle: {
      value: input.collateralCustodyOracle ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.cortex),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.custody),
      getAccountMeta(accounts.custodyTradeOracle),
      getAccountMeta(accounts.collateralCustody),
      getAccountMeta(accounts.collateralCustodyOracle),
    ],
    programAddress,
    data: getGetEntryPriceAndFeeInstructionDataEncoder().encode(
      args as GetEntryPriceAndFeeInstructionDataArgs
    ),
  } as GetEntryPriceAndFeeInstruction<
    TProgramAddress,
    TAccountCortex,
    TAccountPool,
    TAccountCustody,
    TAccountCustodyTradeOracle,
    TAccountCollateralCustody,
    TAccountCollateralCustodyOracle
  >;

  return instruction;
}

export type ParsedGetEntryPriceAndFeeInstruction<
  TProgram extends string = typeof ADRENA_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** #1 */
    cortex: TAccountMetas[0];
    /** #2 */
    pool: TAccountMetas[1];
    /** #3 */
    custody: TAccountMetas[2];
    /** #4 */
    custodyTradeOracle: TAccountMetas[3];
    /** #5 */
    collateralCustody: TAccountMetas[4];
    /** #6 */
    collateralCustodyOracle: TAccountMetas[5];
  };
  data: GetEntryPriceAndFeeInstructionData;
};

export function parseGetEntryPriceAndFeeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedGetEntryPriceAndFeeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      cortex: getNextAccount(),
      pool: getNextAccount(),
      custody: getNextAccount(),
      custodyTradeOracle: getNextAccount(),
      collateralCustody: getNextAccount(),
      collateralCustodyOracle: getNextAccount(),
    },
    data: getGetEntryPriceAndFeeInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
