/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';
import { ADRENA_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';
import {
  getChaosLabsBatchPricesDecoder,
  getChaosLabsBatchPricesEncoder,
  type ChaosLabsBatchPrices,
  type ChaosLabsBatchPricesArgs,
} from '../types';

export const GET_LIQUIDATION_STATE_DISCRIMINATOR = new Uint8Array([
  127, 126, 199, 117, 90, 89, 29, 50,
]);

export function getGetLiquidationStateDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    GET_LIQUIDATION_STATE_DISCRIMINATOR
  );
}

export type GetLiquidationStateInstruction<
  TProgram extends string = typeof ADRENA_PROGRAM_ADDRESS,
  TAccountCortex extends string | IAccountMeta<string> = string,
  TAccountPool extends string | IAccountMeta<string> = string,
  TAccountPosition extends string | IAccountMeta<string> = string,
  TAccountCustody extends string | IAccountMeta<string> = string,
  TAccountOracle extends string | IAccountMeta<string> = string,
  TAccountCollateralCustody extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountCortex extends string
        ? ReadonlyAccount<TAccountCortex>
        : TAccountCortex,
      TAccountPool extends string
        ? ReadonlyAccount<TAccountPool>
        : TAccountPool,
      TAccountPosition extends string
        ? ReadonlyAccount<TAccountPosition>
        : TAccountPosition,
      TAccountCustody extends string
        ? ReadonlyAccount<TAccountCustody>
        : TAccountCustody,
      TAccountOracle extends string
        ? ReadonlyAccount<TAccountOracle>
        : TAccountOracle,
      TAccountCollateralCustody extends string
        ? ReadonlyAccount<TAccountCollateralCustody>
        : TAccountCollateralCustody,
      ...TRemainingAccounts,
    ]
  >;

export type GetLiquidationStateInstructionData = {
  discriminator: ReadonlyUint8Array;
  oraclePrices: Option<ChaosLabsBatchPrices>;
};

export type GetLiquidationStateInstructionDataArgs = {
  oraclePrices: OptionOrNullable<ChaosLabsBatchPricesArgs>;
};

export function getGetLiquidationStateInstructionDataEncoder(): Encoder<GetLiquidationStateInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['oraclePrices', getOptionEncoder(getChaosLabsBatchPricesEncoder())],
    ]),
    (value) => ({
      ...value,
      discriminator: GET_LIQUIDATION_STATE_DISCRIMINATOR,
    })
  );
}

export function getGetLiquidationStateInstructionDataDecoder(): Decoder<GetLiquidationStateInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['oraclePrices', getOptionDecoder(getChaosLabsBatchPricesDecoder())],
  ]);
}

export function getGetLiquidationStateInstructionDataCodec(): Codec<
  GetLiquidationStateInstructionDataArgs,
  GetLiquidationStateInstructionData
> {
  return combineCodec(
    getGetLiquidationStateInstructionDataEncoder(),
    getGetLiquidationStateInstructionDataDecoder()
  );
}

export type GetLiquidationStateInput<
  TAccountCortex extends string = string,
  TAccountPool extends string = string,
  TAccountPosition extends string = string,
  TAccountCustody extends string = string,
  TAccountOracle extends string = string,
  TAccountCollateralCustody extends string = string,
> = {
  /** #1 */
  cortex: Address<TAccountCortex>;
  /** #2 */
  pool: Address<TAccountPool>;
  /** #3 */
  position: Address<TAccountPosition>;
  /** #4 */
  custody: Address<TAccountCustody>;
  /** #5 */
  oracle: Address<TAccountOracle>;
  /** #6 */
  collateralCustody: Address<TAccountCollateralCustody>;
  oraclePrices: GetLiquidationStateInstructionDataArgs['oraclePrices'];
};

export function getGetLiquidationStateInstruction<
  TAccountCortex extends string,
  TAccountPool extends string,
  TAccountPosition extends string,
  TAccountCustody extends string,
  TAccountOracle extends string,
  TAccountCollateralCustody extends string,
  TProgramAddress extends Address = typeof ADRENA_PROGRAM_ADDRESS,
>(
  input: GetLiquidationStateInput<
    TAccountCortex,
    TAccountPool,
    TAccountPosition,
    TAccountCustody,
    TAccountOracle,
    TAccountCollateralCustody
  >,
  config?: { programAddress?: TProgramAddress }
): GetLiquidationStateInstruction<
  TProgramAddress,
  TAccountCortex,
  TAccountPool,
  TAccountPosition,
  TAccountCustody,
  TAccountOracle,
  TAccountCollateralCustody
> {
  // Program address.
  const programAddress = config?.programAddress ?? ADRENA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    cortex: { value: input.cortex ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: false },
    position: { value: input.position ?? null, isWritable: false },
    custody: { value: input.custody ?? null, isWritable: false },
    oracle: { value: input.oracle ?? null, isWritable: false },
    collateralCustody: {
      value: input.collateralCustody ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.cortex),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.custody),
      getAccountMeta(accounts.oracle),
      getAccountMeta(accounts.collateralCustody),
    ],
    programAddress,
    data: getGetLiquidationStateInstructionDataEncoder().encode(
      args as GetLiquidationStateInstructionDataArgs
    ),
  } as GetLiquidationStateInstruction<
    TProgramAddress,
    TAccountCortex,
    TAccountPool,
    TAccountPosition,
    TAccountCustody,
    TAccountOracle,
    TAccountCollateralCustody
  >;

  return instruction;
}

export type ParsedGetLiquidationStateInstruction<
  TProgram extends string = typeof ADRENA_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** #1 */
    cortex: TAccountMetas[0];
    /** #2 */
    pool: TAccountMetas[1];
    /** #3 */
    position: TAccountMetas[2];
    /** #4 */
    custody: TAccountMetas[3];
    /** #5 */
    oracle: TAccountMetas[4];
    /** #6 */
    collateralCustody: TAccountMetas[5];
  };
  data: GetLiquidationStateInstructionData;
};

export function parseGetLiquidationStateInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedGetLiquidationStateInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      cortex: getNextAccount(),
      pool: getNextAccount(),
      position: getNextAccount(),
      custody: getNextAccount(),
      oracle: getNextAccount(),
      collateralCustody: getNextAccount(),
    },
    data: getGetLiquidationStateInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
