/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';
import { ADRENA_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const GET_REMOVE_LIQUIDITY_AMOUNT_AND_FEE_DISCRIMINATOR = new Uint8Array(
  [194, 226, 233, 102, 14, 21, 196, 7]
);

export function getGetRemoveLiquidityAmountAndFeeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    GET_REMOVE_LIQUIDITY_AMOUNT_AND_FEE_DISCRIMINATOR
  );
}

export type GetRemoveLiquidityAmountAndFeeInstruction<
  TProgram extends string = typeof ADRENA_PROGRAM_ADDRESS,
  TAccountCortex extends string | IAccountMeta<string> = string,
  TAccountPool extends string | IAccountMeta<string> = string,
  TAccountCustody extends string | IAccountMeta<string> = string,
  TAccountCustodyOracle extends string | IAccountMeta<string> = string,
  TAccountLpTokenMint extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountCortex extends string
        ? ReadonlyAccount<TAccountCortex>
        : TAccountCortex,
      TAccountPool extends string
        ? ReadonlyAccount<TAccountPool>
        : TAccountPool,
      TAccountCustody extends string
        ? ReadonlyAccount<TAccountCustody>
        : TAccountCustody,
      TAccountCustodyOracle extends string
        ? ReadonlyAccount<TAccountCustodyOracle>
        : TAccountCustodyOracle,
      TAccountLpTokenMint extends string
        ? ReadonlyAccount<TAccountLpTokenMint>
        : TAccountLpTokenMint,
      ...TRemainingAccounts,
    ]
  >;

export type GetRemoveLiquidityAmountAndFeeInstructionData = {
  discriminator: ReadonlyUint8Array;
  lpAmountIn: bigint;
};

export type GetRemoveLiquidityAmountAndFeeInstructionDataArgs = {
  lpAmountIn: number | bigint;
};

export function getGetRemoveLiquidityAmountAndFeeInstructionDataEncoder(): Encoder<GetRemoveLiquidityAmountAndFeeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['lpAmountIn', getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: GET_REMOVE_LIQUIDITY_AMOUNT_AND_FEE_DISCRIMINATOR,
    })
  );
}

export function getGetRemoveLiquidityAmountAndFeeInstructionDataDecoder(): Decoder<GetRemoveLiquidityAmountAndFeeInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['lpAmountIn', getU64Decoder()],
  ]);
}

export function getGetRemoveLiquidityAmountAndFeeInstructionDataCodec(): Codec<
  GetRemoveLiquidityAmountAndFeeInstructionDataArgs,
  GetRemoveLiquidityAmountAndFeeInstructionData
> {
  return combineCodec(
    getGetRemoveLiquidityAmountAndFeeInstructionDataEncoder(),
    getGetRemoveLiquidityAmountAndFeeInstructionDataDecoder()
  );
}

export type GetRemoveLiquidityAmountAndFeeInput<
  TAccountCortex extends string = string,
  TAccountPool extends string = string,
  TAccountCustody extends string = string,
  TAccountCustodyOracle extends string = string,
  TAccountLpTokenMint extends string = string,
> = {
  /** #1 */
  cortex: Address<TAccountCortex>;
  /** #2 */
  pool: Address<TAccountPool>;
  /** #3 */
  custody: Address<TAccountCustody>;
  /** #4 */
  custodyOracle: Address<TAccountCustodyOracle>;
  /** #5 */
  lpTokenMint: Address<TAccountLpTokenMint>;
  lpAmountIn: GetRemoveLiquidityAmountAndFeeInstructionDataArgs['lpAmountIn'];
};

export function getGetRemoveLiquidityAmountAndFeeInstruction<
  TAccountCortex extends string,
  TAccountPool extends string,
  TAccountCustody extends string,
  TAccountCustodyOracle extends string,
  TAccountLpTokenMint extends string,
  TProgramAddress extends Address = typeof ADRENA_PROGRAM_ADDRESS,
>(
  input: GetRemoveLiquidityAmountAndFeeInput<
    TAccountCortex,
    TAccountPool,
    TAccountCustody,
    TAccountCustodyOracle,
    TAccountLpTokenMint
  >,
  config?: { programAddress?: TProgramAddress }
): GetRemoveLiquidityAmountAndFeeInstruction<
  TProgramAddress,
  TAccountCortex,
  TAccountPool,
  TAccountCustody,
  TAccountCustodyOracle,
  TAccountLpTokenMint
> {
  // Program address.
  const programAddress = config?.programAddress ?? ADRENA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    cortex: { value: input.cortex ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: false },
    custody: { value: input.custody ?? null, isWritable: false },
    custodyOracle: { value: input.custodyOracle ?? null, isWritable: false },
    lpTokenMint: { value: input.lpTokenMint ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.cortex),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.custody),
      getAccountMeta(accounts.custodyOracle),
      getAccountMeta(accounts.lpTokenMint),
    ],
    programAddress,
    data: getGetRemoveLiquidityAmountAndFeeInstructionDataEncoder().encode(
      args as GetRemoveLiquidityAmountAndFeeInstructionDataArgs
    ),
  } as GetRemoveLiquidityAmountAndFeeInstruction<
    TProgramAddress,
    TAccountCortex,
    TAccountPool,
    TAccountCustody,
    TAccountCustodyOracle,
    TAccountLpTokenMint
  >;

  return instruction;
}

export type ParsedGetRemoveLiquidityAmountAndFeeInstruction<
  TProgram extends string = typeof ADRENA_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** #1 */
    cortex: TAccountMetas[0];
    /** #2 */
    pool: TAccountMetas[1];
    /** #3 */
    custody: TAccountMetas[2];
    /** #4 */
    custodyOracle: TAccountMetas[3];
    /** #5 */
    lpTokenMint: TAccountMetas[4];
  };
  data: GetRemoveLiquidityAmountAndFeeInstructionData;
};

export function parseGetRemoveLiquidityAmountAndFeeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedGetRemoveLiquidityAmountAndFeeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      cortex: getNextAccount(),
      pool: getNextAccount(),
      custody: getNextAccount(),
      custodyOracle: getNextAccount(),
      lpTokenMint: getNextAccount(),
    },
    data: getGetRemoveLiquidityAmountAndFeeInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
