/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { ADRENA_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const MIGRATE_VEST_FROM_V1_TO_V2_DISCRIMINATOR = new Uint8Array([
  111, 209, 73, 40, 58, 206, 244, 147,
]);

export function getMigrateVestFromV1ToV2DiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    MIGRATE_VEST_FROM_V1_TO_V2_DISCRIMINATOR
  );
}

export type MigrateVestFromV1ToV2Instruction<
  TProgram extends string = typeof ADRENA_PROGRAM_ADDRESS,
  TAccountCaller extends string | IAccountMeta<string> = string,
  TAccountOwner extends string | IAccountMeta<string> = string,
  TAccountPayer extends string | IAccountMeta<string> = string,
  TAccountVest extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TAccountTokenProgram extends
    | string
    | IAccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountRent extends
    | string
    | IAccountMeta<string> = 'SysvarRent111111111111111111111111111111111',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountCaller extends string
        ? ReadonlySignerAccount<TAccountCaller> &
            IAccountSignerMeta<TAccountCaller>
        : TAccountCaller,
      TAccountOwner extends string
        ? ReadonlyAccount<TAccountOwner>
        : TAccountOwner,
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            IAccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountVest extends string
        ? WritableAccount<TAccountVest>
        : TAccountVest,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountRent extends string
        ? ReadonlyAccount<TAccountRent>
        : TAccountRent,
      ...TRemainingAccounts,
    ]
  >;

export type MigrateVestFromV1ToV2InstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type MigrateVestFromV1ToV2InstructionDataArgs = {};

export function getMigrateVestFromV1ToV2InstructionDataEncoder(): Encoder<MigrateVestFromV1ToV2InstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: MIGRATE_VEST_FROM_V1_TO_V2_DISCRIMINATOR,
    })
  );
}

export function getMigrateVestFromV1ToV2InstructionDataDecoder(): Decoder<MigrateVestFromV1ToV2InstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getMigrateVestFromV1ToV2InstructionDataCodec(): Codec<
  MigrateVestFromV1ToV2InstructionDataArgs,
  MigrateVestFromV1ToV2InstructionData
> {
  return combineCodec(
    getMigrateVestFromV1ToV2InstructionDataEncoder(),
    getMigrateVestFromV1ToV2InstructionDataDecoder()
  );
}

export type MigrateVestFromV1ToV2Input<
  TAccountCaller extends string = string,
  TAccountOwner extends string = string,
  TAccountPayer extends string = string,
  TAccountVest extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountRent extends string = string,
> = {
  /**
   * #1
   * The caller of this instruction
   */
  caller: TransactionSigner<TAccountCaller>;
  /**
   * #2
   * Wallet related to the vest
   */
  owner: Address<TAccountOwner>;
  /**
   * #3
   * Account paying for the reallocation
   */
  payer: TransactionSigner<TAccountPayer>;
  /** #4 */
  vest: Address<TAccountVest>;
  /** #5 */
  systemProgram?: Address<TAccountSystemProgram>;
  /** #6 */
  tokenProgram?: Address<TAccountTokenProgram>;
  /** #7 */
  rent?: Address<TAccountRent>;
};

export function getMigrateVestFromV1ToV2Instruction<
  TAccountCaller extends string,
  TAccountOwner extends string,
  TAccountPayer extends string,
  TAccountVest extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof ADRENA_PROGRAM_ADDRESS,
>(
  input: MigrateVestFromV1ToV2Input<
    TAccountCaller,
    TAccountOwner,
    TAccountPayer,
    TAccountVest,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress }
): MigrateVestFromV1ToV2Instruction<
  TProgramAddress,
  TAccountCaller,
  TAccountOwner,
  TAccountPayer,
  TAccountVest,
  TAccountSystemProgram,
  TAccountTokenProgram,
  TAccountRent
> {
  // Program address.
  const programAddress = config?.programAddress ?? ADRENA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: false },
    owner: { value: input.owner ?? null, isWritable: false },
    payer: { value: input.payer ?? null, isWritable: true },
    vest: { value: input.vest ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      'SysvarRent111111111111111111111111111111111' as Address<'SysvarRent111111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.caller),
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.vest),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.rent),
    ],
    programAddress,
    data: getMigrateVestFromV1ToV2InstructionDataEncoder().encode({}),
  } as MigrateVestFromV1ToV2Instruction<
    TProgramAddress,
    TAccountCaller,
    TAccountOwner,
    TAccountPayer,
    TAccountVest,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >;

  return instruction;
}

export type ParsedMigrateVestFromV1ToV2Instruction<
  TProgram extends string = typeof ADRENA_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /**
     * #1
     * The caller of this instruction
     */

    caller: TAccountMetas[0];
    /**
     * #2
     * Wallet related to the vest
     */

    owner: TAccountMetas[1];
    /**
     * #3
     * Account paying for the reallocation
     */

    payer: TAccountMetas[2];
    /** #4 */
    vest: TAccountMetas[3];
    /** #5 */
    systemProgram: TAccountMetas[4];
    /** #6 */
    tokenProgram: TAccountMetas[5];
    /** #7 */
    rent: TAccountMetas[6];
  };
  data: MigrateVestFromV1ToV2InstructionData;
};

export function parseMigrateVestFromV1ToV2Instruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedMigrateVestFromV1ToV2Instruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      caller: getNextAccount(),
      owner: getNextAccount(),
      payer: getNextAccount(),
      vest: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      rent: getNextAccount(),
    },
    data: getMigrateVestFromV1ToV2InstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
