/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { ADRENA_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const SET_CUSTODY_ALLOW_SWAP_DISCRIMINATOR = new Uint8Array([
  70, 172, 206, 130, 229, 55, 110, 97,
]);

export function getSetCustodyAllowSwapDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SET_CUSTODY_ALLOW_SWAP_DISCRIMINATOR
  );
}

export type SetCustodyAllowSwapInstruction<
  TProgram extends string = typeof ADRENA_PROGRAM_ADDRESS,
  TAccountAdmin extends string | IAccountMeta<string> = string,
  TAccountCortex extends string | IAccountMeta<string> = string,
  TAccountPool extends string | IAccountMeta<string> = string,
  TAccountCustody extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            IAccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountCortex extends string
        ? WritableAccount<TAccountCortex>
        : TAccountCortex,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      TAccountCustody extends string
        ? WritableAccount<TAccountCustody>
        : TAccountCustody,
      ...TRemainingAccounts,
    ]
  >;

export type SetCustodyAllowSwapInstructionData = {
  discriminator: ReadonlyUint8Array;
  allowSwap: boolean;
};

export type SetCustodyAllowSwapInstructionDataArgs = { allowSwap: boolean };

export function getSetCustodyAllowSwapInstructionDataEncoder(): Encoder<SetCustodyAllowSwapInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['allowSwap', getBooleanEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: SET_CUSTODY_ALLOW_SWAP_DISCRIMINATOR,
    })
  );
}

export function getSetCustodyAllowSwapInstructionDataDecoder(): Decoder<SetCustodyAllowSwapInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['allowSwap', getBooleanDecoder()],
  ]);
}

export function getSetCustodyAllowSwapInstructionDataCodec(): Codec<
  SetCustodyAllowSwapInstructionDataArgs,
  SetCustodyAllowSwapInstructionData
> {
  return combineCodec(
    getSetCustodyAllowSwapInstructionDataEncoder(),
    getSetCustodyAllowSwapInstructionDataDecoder()
  );
}

export type SetCustodyAllowSwapInput<
  TAccountAdmin extends string = string,
  TAccountCortex extends string = string,
  TAccountPool extends string = string,
  TAccountCustody extends string = string,
> = {
  /** #1 */
  admin: TransactionSigner<TAccountAdmin>;
  /** #2 */
  cortex: Address<TAccountCortex>;
  /** #3 */
  pool: Address<TAccountPool>;
  /** #4 */
  custody: Address<TAccountCustody>;
  allowSwap: SetCustodyAllowSwapInstructionDataArgs['allowSwap'];
};

export function getSetCustodyAllowSwapInstruction<
  TAccountAdmin extends string,
  TAccountCortex extends string,
  TAccountPool extends string,
  TAccountCustody extends string,
  TProgramAddress extends Address = typeof ADRENA_PROGRAM_ADDRESS,
>(
  input: SetCustodyAllowSwapInput<
    TAccountAdmin,
    TAccountCortex,
    TAccountPool,
    TAccountCustody
  >,
  config?: { programAddress?: TProgramAddress }
): SetCustodyAllowSwapInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountCortex,
  TAccountPool,
  TAccountCustody
> {
  // Program address.
  const programAddress = config?.programAddress ?? ADRENA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: false },
    cortex: { value: input.cortex ?? null, isWritable: true },
    pool: { value: input.pool ?? null, isWritable: true },
    custody: { value: input.custody ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.cortex),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.custody),
    ],
    programAddress,
    data: getSetCustodyAllowSwapInstructionDataEncoder().encode(
      args as SetCustodyAllowSwapInstructionDataArgs
    ),
  } as SetCustodyAllowSwapInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountCortex,
    TAccountPool,
    TAccountCustody
  >;

  return instruction;
}

export type ParsedSetCustodyAllowSwapInstruction<
  TProgram extends string = typeof ADRENA_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** #1 */
    admin: TAccountMetas[0];
    /** #2 */
    cortex: TAccountMetas[1];
    /** #3 */
    pool: TAccountMetas[2];
    /** #4 */
    custody: TAccountMetas[3];
  };
  data: SetCustodyAllowSwapInstructionData;
};

export function parseSetCustodyAllowSwapInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedSetCustodyAllowSwapInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      cortex: getNextAccount(),
      pool: getNextAccount(),
      custody: getNextAccount(),
    },
    data: getSetCustodyAllowSwapInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
