/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { ADRENA_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const SET_POOL_AUM_SOFT_CAP_USD_DISCRIMINATOR = new Uint8Array([
  124, 194, 30, 229, 89, 235, 94, 38,
]);

export function getSetPoolAumSoftCapUsdDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SET_POOL_AUM_SOFT_CAP_USD_DISCRIMINATOR
  );
}

export type SetPoolAumSoftCapUsdInstruction<
  TProgram extends string = typeof ADRENA_PROGRAM_ADDRESS,
  TAccountAdmin extends string | IAccountMeta<string> = string,
  TAccountCortex extends string | IAccountMeta<string> = string,
  TAccountPool extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            IAccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountCortex extends string
        ? WritableAccount<TAccountCortex>
        : TAccountCortex,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      ...TRemainingAccounts,
    ]
  >;

export type SetPoolAumSoftCapUsdInstructionData = {
  discriminator: ReadonlyUint8Array;
  aumSoftCapUsd: bigint;
};

export type SetPoolAumSoftCapUsdInstructionDataArgs = {
  aumSoftCapUsd: number | bigint;
};

export function getSetPoolAumSoftCapUsdInstructionDataEncoder(): Encoder<SetPoolAumSoftCapUsdInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['aumSoftCapUsd', getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: SET_POOL_AUM_SOFT_CAP_USD_DISCRIMINATOR,
    })
  );
}

export function getSetPoolAumSoftCapUsdInstructionDataDecoder(): Decoder<SetPoolAumSoftCapUsdInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['aumSoftCapUsd', getU64Decoder()],
  ]);
}

export function getSetPoolAumSoftCapUsdInstructionDataCodec(): Codec<
  SetPoolAumSoftCapUsdInstructionDataArgs,
  SetPoolAumSoftCapUsdInstructionData
> {
  return combineCodec(
    getSetPoolAumSoftCapUsdInstructionDataEncoder(),
    getSetPoolAumSoftCapUsdInstructionDataDecoder()
  );
}

export type SetPoolAumSoftCapUsdInput<
  TAccountAdmin extends string = string,
  TAccountCortex extends string = string,
  TAccountPool extends string = string,
> = {
  /** #1 */
  admin: TransactionSigner<TAccountAdmin>;
  /** #2 */
  cortex: Address<TAccountCortex>;
  /** #3 */
  pool: Address<TAccountPool>;
  aumSoftCapUsd: SetPoolAumSoftCapUsdInstructionDataArgs['aumSoftCapUsd'];
};

export function getSetPoolAumSoftCapUsdInstruction<
  TAccountAdmin extends string,
  TAccountCortex extends string,
  TAccountPool extends string,
  TProgramAddress extends Address = typeof ADRENA_PROGRAM_ADDRESS,
>(
  input: SetPoolAumSoftCapUsdInput<TAccountAdmin, TAccountCortex, TAccountPool>,
  config?: { programAddress?: TProgramAddress }
): SetPoolAumSoftCapUsdInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountCortex,
  TAccountPool
> {
  // Program address.
  const programAddress = config?.programAddress ?? ADRENA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: false },
    cortex: { value: input.cortex ?? null, isWritable: true },
    pool: { value: input.pool ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.cortex),
      getAccountMeta(accounts.pool),
    ],
    programAddress,
    data: getSetPoolAumSoftCapUsdInstructionDataEncoder().encode(
      args as SetPoolAumSoftCapUsdInstructionDataArgs
    ),
  } as SetPoolAumSoftCapUsdInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountCortex,
    TAccountPool
  >;

  return instruction;
}

export type ParsedSetPoolAumSoftCapUsdInstruction<
  TProgram extends string = typeof ADRENA_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** #1 */
    admin: TAccountMetas[0];
    /** #2 */
    cortex: TAccountMetas[1];
    /** #3 */
    pool: TAccountMetas[2];
  };
  data: SetPoolAumSoftCapUsdInstructionData;
};

export function parseSetPoolAumSoftCapUsdInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedSetPoolAumSoftCapUsdInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      cortex: getNextAccount(),
      pool: getNextAccount(),
    },
    data: getSetPoolAumSoftCapUsdInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
