/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export enum Team {
  Default,
  Bonk,
  Jito,
}

export type TeamArgs = Team;

export function getTeamEncoder(): Encoder<TeamArgs> {
  return getEnumEncoder(Team);
}

export function getTeamDecoder(): Decoder<Team> {
  return getEnumDecoder(Team);
}

export function getTeamCodec(): Codec<TeamArgs, Team> {
  return combineCodec(getTeamEncoder(), getTeamDecoder());
}
