/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type TradingStats = {
  openedPositionCount: bigint;
  liquidatedPositionCount: bigint;
  openingAverageLeverage: bigint;
  openingSizeUsd: bigint;
  profitsUsd: bigint;
  lossesUsd: bigint;
  feePaidUsd: bigint;
};

export type TradingStatsArgs = {
  openedPositionCount: number | bigint;
  liquidatedPositionCount: number | bigint;
  openingAverageLeverage: number | bigint;
  openingSizeUsd: number | bigint;
  profitsUsd: number | bigint;
  lossesUsd: number | bigint;
  feePaidUsd: number | bigint;
};

export function getTradingStatsEncoder(): Encoder<TradingStatsArgs> {
  return getStructEncoder([
    ['openedPositionCount', getU64Encoder()],
    ['liquidatedPositionCount', getU64Encoder()],
    ['openingAverageLeverage', getU64Encoder()],
    ['openingSizeUsd', getU64Encoder()],
    ['profitsUsd', getU64Encoder()],
    ['lossesUsd', getU64Encoder()],
    ['feePaidUsd', getU64Encoder()],
  ]);
}

export function getTradingStatsDecoder(): Decoder<TradingStats> {
  return getStructDecoder([
    ['openedPositionCount', getU64Decoder()],
    ['liquidatedPositionCount', getU64Decoder()],
    ['openingAverageLeverage', getU64Decoder()],
    ['openingSizeUsd', getU64Decoder()],
    ['profitsUsd', getU64Decoder()],
    ['lossesUsd', getU64Decoder()],
    ['feePaidUsd', getU64Decoder()],
  ]);
}

export function getTradingStatsCodec(): Codec<TradingStatsArgs, TradingStats> {
  return combineCodec(getTradingStatsEncoder(), getTradingStatsDecoder());
}
