/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type TradeStats = {
  profitUsd: bigint;
  lossUsd: bigint;
  oiLongUsd: bigint;
  oiShortUsd: bigint;
};

export type TradeStatsArgs = {
  profitUsd: number | bigint;
  lossUsd: number | bigint;
  oiLongUsd: number | bigint;
  oiShortUsd: number | bigint;
};

export function getTradeStatsEncoder(): Encoder<TradeStatsArgs> {
  return getStructEncoder([
    ['profitUsd', getU64Encoder()],
    ['lossUsd', getU64Encoder()],
    ['oiLongUsd', getU64Encoder()],
    ['oiShortUsd', getU64Encoder()],
  ]);
}

export function getTradeStatsDecoder(): Decoder<TradeStats> {
  return getStructDecoder([
    ['profitUsd', getU64Decoder()],
    ['lossUsd', getU64Decoder()],
    ['oiLongUsd', getU64Decoder()],
    ['oiShortUsd', getU64Decoder()],
  ]);
}

export function getTradeStatsCodec(): Codec<TradeStatsArgs, TradeStats> {
  return combineCodec(getTradeStatsEncoder(), getTradeStatsDecoder());
}
