/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type U128Split = { high: bigint; low: bigint };

export type U128SplitArgs = { high: number | bigint; low: number | bigint };

export function getU128SplitEncoder(): Encoder<U128SplitArgs> {
  return getStructEncoder([
    ['high', getU64Encoder()],
    ['low', getU64Encoder()],
  ]);
}

export function getU128SplitDecoder(): Decoder<U128Split> {
  return getStructDecoder([
    ['high', getU64Decoder()],
    ['low', getU64Decoder()],
  ]);
}

export function getU128SplitCodec(): Codec<U128SplitArgs, U128Split> {
  return combineCodec(getU128SplitEncoder(), getU128SplitDecoder());
}
